import React from "react";
import { graphqlOperation } from "aws-amplify";
import { Connect } from "aws-amplify-react";
import { Link } from "react-router-dom";
import { Loading, Card, Icon, Tag } from "element-react";
// Manually define ListMarkets GraphQL query due to an alteration when generated by AppSync
// import { listMarkets } from "../graphql/queries";
import { onCreateMarket } from "../graphql/subscriptions";
import Error from "./Error";

const listMarkets = `query ListMarkets(
  $filter: ModelMarketFilterInput
  $limit: Int
  $nextToken: String
) {
  listMarkets(filter: $filter, limit: $limit, nextToken: $nextToken) {
    items {
      id
      name
      products {
        items {
          id
          description
          price
          shipped
          owner
          createdAt
        }
        nextToken
      }
      tags
      owner
      createdAt
    }
    nextToken
  }
}
`;

const MarketList = ({ searchResults, searchComplete }) => {
  const onNewMarket = (prevQuery, newData) => {
    let updatedQuery = { ...prevQuery };
    const updatedMarketList = [
      newData.onCreateMarket,
      ...prevQuery.listMarkets.items,
    ];
    updatedQuery.listMarkets.items = updatedMarketList;
    return updatedQuery;
  };
  return (
    <Connect
      query={graphqlOperation(listMarkets)}
      subscription={graphqlOperation(onCreateMarket)}
      onSubscriptionMsg={onNewMarket}
    >
      {({ data, loading, errors }) => {
        console.log("data ->", data);
        if (errors.length > 0) return <Error errors={errors} />;
        if (loading || !data.listMarkets) return <Loading fullscreen={true} />;
        // TODO : fix bug - if search returns 0 results, should display "0 results" instead of all markets
        const markets = searchComplete ? searchResults : data.listMarkets.items;
        console.log("markets ->", markets);
        return (
          <>
            {searchComplete ? (
              <h2 className="text-green">
                <Icon type="success" name="check" className="icon" />
                {searchResults.length === 1
                  ? "1 Result"
                  : `${searchResults.length} Results`}
              </h2>
            ) : (
              <h2 className="header">Markets</h2>
            )}
            <div className="markets-container">
              {markets.map(market => (
                <div key={market.id} className="my-2">
                  <Card
                    bodyStyle={{
                      display: "grid",
                      padding: "1em",
                      alignItems: "center",
                      justifyContent: "space-between",
                      rowGap: "2rem",
                    }}
                  >
                    <div>
                      <span className="flex">
                        <Link className="link" to={`/markets/${market.id}`}>
                          {market.name}
                        </Link>
                        <span style={{ color: "var(--darkAmazonOrange)" }}>
                          {market.products.items
                            ? market.products.items.length
                            : 0}
                        </span>
                      </span>
                      <div
                        style={{
                          color: "var(--lightSquidInk)",
                          fontSize: "12px",
                        }}
                      >
                        {market.owner}
                      </div>
                    </div>
                    <div>
                      {market.tags &&
                        market.tags.map(tag => (
                          <Tag
                            key={tag}
                            className="mr-1"
                            style={{ backgroundColor: "#c5c5c5" }}
                          >
                            {tag}
                          </Tag>
                        ))}
                    </div>
                  </Card>
                </div>
              ))}
            </div>
          </>
        );
      }}
    </Connect>
  );
};

export default MarketList;
